# [Info]
# 左上角标题
site_name: 陶守忠的个人网站
site_url: https://yang-xijie.github.io
site_author: 陶守忠
site_description: 陶守忠的个人网站


site_name: MkLorum
nav:
  - blog:
    - MkLorum博客: blog/index.md
    - Kingbase: 
      - KDTS迁移：Company-2/Kingbase/KDTS迁移.md
  - About: about.md
