# [Info]
# 左上角标题
site_name: 陶守忠的个人网站
site_url: https://yang-xijie.github.io
site_author: 陶守忠
site_description: 陶守忠的个人网站


#site_name: MkLorum
# Navivation 导航
nav:
  - 文档:
    - index.md
    - Kingbase: 
      - Company-2/Kingbase/KDTS-1.md
    - 东方通:
      - Company-2/东方通/TongWeb.md
  - About: about.md
